export const APPLICATION_STEP_LABELS = [
  "Personal",
  "Nationality",
  "Identity",
  "Parent",
  "Travel & visa",
  "Status & English",
];

export function getInitialApplicationFormData() {
  return {
    applicationType: "Family",
    firstName: "",
    lastName: "",
    email: "",
    gender: "",
    contactNumber: "",
    relationshipStatus: "",
    address: "",
    nationality: "",
    birthCountry: "",
    placeOfBirth: "",
    dob: "",
    passportNumber: "",
    issuingAuthority: "",
    issueDate: "",
    expiryDate: "",
    passportAvailable: "",
    nationalIdCardNumber: "",
    nationalIdNumber: "",
    idIssuingAuthorityCard: "",
    idIssuingAuthorityNational: "",
    otherNationality: "",
    ukLicense: "",
    medicalTreatment: "",
    ukStayDuration: "",
    contactNumber2: "",
    previousFullAddress: "",
    previousAddress: "",
    startDate: "",
    endDate: "",
    parentName: "",
    parentRelation: "",
    parentDob: "",
    parentNationality: "",
    sameNationality: "",
    parent2Name: "",
    parent2Relation: "",
    parent2Dob: "",
    parent2Nationality: "",
    parent2SameNationality: "",
    illegalEntry: "",
    overstayed: "",
    breach: "",
    falseInfo: "",
    otherBreach: "",
    refusedVisa: "",
    refusedEntry: "",
    refusedPermission: "",
    refusedAsylum: "",
    deported: "",
    removed: "",
    requiredToLeave: "",
    banned: "",
    visitedOther: "",
    countryVisited: "",
    visitReason: "",
    entryDate: "",
    leaveDate: "",
    visaType: "",
    brpNumber: "",
    visaEndDate: "",
    niNumber: "",
    sponsored: "",
    englishProof: "",
  };
}
