import { isValidPhoneNumber } from "libphonenumber-js";

export const COUNTRIES = [
  {
    code: "AF",
    name: "Afghanistan",
    nationality: "Afghan",
    dialCode: "+93",
    flag: "🇦🇫",
  },
  {
    code: "AL",
    name: "Albania",
    nationality: "Albanian",
    dialCode: "+355",
    flag: "🇦🇱",
  },
  {
    code: "DZ",
    name: "Algeria",
    nationality: "Algerian",
    dialCode: "+213",
    flag: "🇩🇿",
  },
  {
    code: "AR",
    name: "Argentina",
    nationality: "Argentine",
    dialCode: "+54",
    flag: "🇦🇷",
  },
  {
    code: "AU",
    name: "Australia",
    nationality: "Australian",
    dialCode: "+61",
    flag: "🇦🇺",
  },
  {
    code: "AT",
    name: "Austria",
    nationality: "Austrian",
    dialCode: "+43",
    flag: "🇦🇹",
  },
  {
    code: "BD",
    name: "Bangladesh",
    nationality: "Bangladeshi",
    dialCode: "+880",
    flag: "🇧🇩",
  },
  {
    code: "BE",
    name: "Belgium",
    nationality: "Belgian",
    dialCode: "+32",
    flag: "🇧🇪",
  },
  {
    code: "BR",
    name: "Brazil",
    nationality: "Brazilian",
    dialCode: "+55",
    flag: "🇧🇷",
  },
  {
    code: "BG",
    name: "Bulgaria",
    nationality: "Bulgarian",
    dialCode: "+359",
    flag: "🇧🇬",
  },
  {
    code: "CA",
    name: "Canada",
    nationality: "Canadian",
    dialCode: "+1",
    flag: "🇨🇦",
  },
  {
    code: "CN",
    name: "China",
    nationality: "Chinese",
    dialCode: "+86",
    flag: "🇨🇳",
  },
  {
    code: "CO",
    name: "Colombia",
    nationality: "Colombian",
    dialCode: "+57",
    flag: "🇨🇴",
  },
  {
    code: "HR",
    name: "Croatia",
    nationality: "Croatian",
    dialCode: "+385",
    flag: "🇭🇷",
  },
  {
    code: "CU",
    name: "Cuba",
    nationality: "Cuban",
    dialCode: "+53",
    flag: "🇨🇺",
  },
  {
    code: "CY",
    name: "Cyprus",
    nationality: "Cypriot",
    dialCode: "+357",
    flag: "🇨🇾",
  },
  {
    code: "CZ",
    name: "Czechia",
    nationality: "Czech",
    dialCode: "+420",
    flag: "🇨🇿",
  },
  {
    code: "DK",
    name: "Denmark",
    nationality: "Danish",
    dialCode: "+45",
    flag: "🇩🇰",
  },
  {
    code: "EG",
    name: "Egypt",
    nationality: "Egyptian",
    dialCode: "+20",
    flag: "🇪🇬",
  },
  {
    code: "EE",
    name: "Estonia",
    nationality: "Estonian",
    dialCode: "+372",
    flag: "🇪🇪",
  },
  {
    code: "ET",
    name: "Ethiopia",
    nationality: "Ethiopian",
    dialCode: "+251",
    flag: "🇪🇹",
  },
  {
    code: "FI",
    name: "Finland",
    nationality: "Finnish",
    dialCode: "+358",
    flag: "🇫🇮",
  },
  {
    code: "FR",
    name: "France",
    nationality: "French",
    dialCode: "+33",
    flag: "🇫🇷",
  },
  {
    code: "DE",
    name: "Germany",
    nationality: "German",
    dialCode: "+49",
    flag: "🇩🇪",
  },
  {
    code: "GH",
    name: "Ghana",
    nationality: "Ghanaian",
    dialCode: "+233",
    flag: "🇬🇭",
  },
  {
    code: "GR",
    name: "Greece",
    nationality: "Greek",
    dialCode: "+30",
    flag: "🇬🇷",
  },
  {
    code: "HK",
    name: "Hong Kong",
    nationality: "Hong Konger",
    dialCode: "+852",
    flag: "🇭🇰",
  },
  {
    code: "HU",
    name: "Hungary",
    nationality: "Hungarian",
    dialCode: "+36",
    flag: "🇭🇺",
  },
  {
    code: "IS",
    name: "Iceland",
    nationality: "Icelandic",
    dialCode: "+354",
    flag: "🇮🇸",
  },
  {
    code: "IN",
    name: "India",
    nationality: "Indian",
    dialCode: "+91",
    flag: "🇮🇳",
  },
  {
    code: "ID",
    name: "Indonesia",
    nationality: "Indonesian",
    dialCode: "+62",
    flag: "🇮🇩",
  },
  {
    code: "IR",
    name: "Iran",
    nationality: "Iranian",
    dialCode: "+98",
    flag: "🇮🇷",
  },
  {
    code: "IQ",
    name: "Iraq",
    nationality: "Iraqi",
    dialCode: "+964",
    flag: "🇮🇶",
  },
  {
    code: "IE",
    name: "Ireland",
    nationality: "Irish",
    dialCode: "+353",
    flag: "🇮🇪",
  },
  {
    code: "IL",
    name: "Israel",
    nationality: "Israeli",
    dialCode: "+972",
    flag: "🇮🇱",
  },
  {
    code: "IT",
    name: "Italy",
    nationality: "Italian",
    dialCode: "+39",
    flag: "🇮🇹",
  },
  {
    code: "JM",
    name: "Jamaica",
    nationality: "Jamaican",
    dialCode: "+1",
    flag: "🇯🇲",
  },
  {
    code: "JP",
    name: "Japan",
    nationality: "Japanese",
    dialCode: "+81",
    flag: "🇯🇵",
  },
  {
    code: "JO",
    name: "Jordan",
    nationality: "Jordanian",
    dialCode: "+962",
    flag: "🇯🇴",
  },
  {
    code: "KE",
    name: "Kenya",
    nationality: "Kenyan",
    dialCode: "+254",
    flag: "🇰🇪",
  },
  {
    code: "KW",
    name: "Kuwait",
    nationality: "Kuwaiti",
    dialCode: "+965",
    flag: "🇰🇼",
  },
  {
    code: "LV",
    name: "Latvia",
    nationality: "Latvian",
    dialCode: "+371",
    flag: "🇱🇻",
  },
  {
    code: "LB",
    name: "Lebanon",
    nationality: "Lebanese",
    dialCode: "+961",
    flag: "🇱🇧",
  },
  {
    code: "LT",
    name: "Lithuania",
    nationality: "Lithuanian",
    dialCode: "+370",
    flag: "🇱🇹",
  },
  {
    code: "LU",
    name: "Luxembourg",
    nationality: "Luxembourgish",
    dialCode: "+352",
    flag: "🇱🇺",
  },
  {
    code: "MY",
    name: "Malaysia",
    nationality: "Malaysian",
    dialCode: "+60",
    flag: "🇲🇾",
  },
  {
    code: "MT",
    name: "Malta",
    nationality: "Maltese",
    dialCode: "+356",
    flag: "🇲🇹",
  },
  {
    code: "MX",
    name: "Mexico",
    nationality: "Mexican",
    dialCode: "+52",
    flag: "🇲🇽",
  },
  {
    code: "MA",
    name: "Morocco",
    nationality: "Moroccan",
    dialCode: "+212",
    flag: "🇲🇦",
  },
  {
    code: "NP",
    name: "Nepal",
    nationality: "Nepali",
    dialCode: "+977",
    flag: "🇳🇵",
  },
  {
    code: "NL",
    name: "Netherlands",
    nationality: "Dutch",
    dialCode: "+31",
    flag: "🇳🇱",
  },
  {
    code: "NZ",
    name: "New Zealand",
    nationality: "New Zealander",
    dialCode: "+64",
    flag: "🇳🇿",
  },
  {
    code: "NG",
    name: "Nigeria",
    nationality: "Nigerian",
    dialCode: "+234",
    flag: "🇳🇬",
  },
  {
    code: "NO",
    name: "Norway",
    nationality: "Norwegian",
    dialCode: "+47",
    flag: "🇳🇴",
  },
  {
    code: "PK",
    name: "Pakistan",
    nationality: "Pakistani",
    dialCode: "+92",
    flag: "🇵🇰",
  },
  {
    code: "PS",
    name: "Palestine",
    nationality: "Palestinian",
    dialCode: "+970",
    flag: "🇵🇸",
  },
  {
    code: "PH",
    name: "Philippines",
    nationality: "Filipino",
    dialCode: "+63",
    flag: "🇵🇭",
  },
  {
    code: "PL",
    name: "Poland",
    nationality: "Polish",
    dialCode: "+48",
    flag: "🇵🇱",
  },
  {
    code: "PT",
    name: "Portugal",
    nationality: "Portuguese",
    dialCode: "+351",
    flag: "🇵🇹",
  },
  {
    code: "QA",
    name: "Qatar",
    nationality: "Qatari",
    dialCode: "+974",
    flag: "🇶🇦",
  },
  {
    code: "RO",
    name: "Romania",
    nationality: "Romanian",
    dialCode: "+40",
    flag: "🇷🇴",
  },
  {
    code: "RU",
    name: "Russia",
    nationality: "Russian",
    dialCode: "+7",
    flag: "🇷🇺",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    nationality: "Saudi",
    dialCode: "+966",
    flag: "🇸🇦",
  },
  {
    code: "RS",
    name: "Serbia",
    nationality: "Serbian",
    dialCode: "+381",
    flag: "🇷🇸",
  },
  {
    code: "SG",
    name: "Singapore",
    nationality: "Singaporean",
    dialCode: "+65",
    flag: "🇸🇬",
  },
  {
    code: "SK",
    name: "Slovakia",
    nationality: "Slovak",
    dialCode: "+421",
    flag: "🇸🇰",
  },
  {
    code: "SI",
    name: "Slovenia",
    nationality: "Slovenian",
    dialCode: "+386",
    flag: "🇸🇮",
  },
  {
    code: "ZA",
    name: "South Africa",
    nationality: "South African",
    dialCode: "+27",
    flag: "🇿🇦",
  },
  {
    code: "KR",
    name: "South Korea",
    nationality: "South Korean",
    dialCode: "+82",
    flag: "🇰🇷",
  },
  {
    code: "ES",
    name: "Spain",
    nationality: "Spanish",
    dialCode: "+34",
    flag: "🇪🇸",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    nationality: "Sri Lankan",
    dialCode: "+94",
    flag: "🇱🇰",
  },
  {
    code: "SE",
    name: "Sweden",
    nationality: "Swedish",
    dialCode: "+46",
    flag: "🇸🇪",
  },
  {
    code: "CH",
    name: "Switzerland",
    nationality: "Swiss",
    dialCode: "+41",
    flag: "🇨🇭",
  },
  {
    code: "SY",
    name: "Syria",
    nationality: "Syrian",
    dialCode: "+963",
    flag: "🇸🇾",
  },
  {
    code: "TW",
    name: "Taiwan",
    nationality: "Taiwanese",
    dialCode: "+886",
    flag: "🇹🇼",
  },
  {
    code: "TZ",
    name: "Tanzania",
    nationality: "Tanzanian",
    dialCode: "+255",
    flag: "🇹🇿",
  },
  {
    code: "TH",
    name: "Thailand",
    nationality: "Thai",
    dialCode: "+66",
    flag: "🇹🇭",
  },
  {
    code: "TN",
    name: "Tunisia",
    nationality: "Tunisian",
    dialCode: "+216",
    flag: "🇹🇳",
  },
  {
    code: "TR",
    name: "Turkey",
    nationality: "Turkish",
    dialCode: "+90",
    flag: "🇹🇷",
  },
  {
    code: "UG",
    name: "Uganda",
    nationality: "Ugandan",
    dialCode: "+256",
    flag: "🇺🇬",
  },
  {
    code: "UA",
    name: "Ukraine",
    nationality: "Ukrainian",
    dialCode: "+380",
    flag: "🇺🇦",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    nationality: "Emirati",
    dialCode: "+971",
    flag: "🇦🇪",
  },
  {
    code: "GB",
    name: "United Kingdom",
    nationality: "British",
    dialCode: "+44",
    flag: "🇬🇧",
  },
  {
    code: "US",
    name: "United States",
    nationality: "American",
    dialCode: "+1",
    flag: "🇺🇸",
  },
  {
    code: "VN",
    name: "Vietnam",
    nationality: "Vietnamese",
    dialCode: "+84",
    flag: "🇻🇳",
  },
  {
    code: "YE",
    name: "Yemen",
    nationality: "Yemeni",
    dialCode: "+967",
    flag: "🇾🇪",
  },
  {
    code: "ZM",
    name: "Zambia",
    nationality: "Zambian",
    dialCode: "+260",
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    nationality: "Zimbabwean",
    dialCode: "+263",
    flag: "🇿🇼",
  },
  // ── Full ISO 3166-1 coverage (BUG-006). Entries above are the original curated
  // list and are kept unchanged; everything below was generated from the ISO
  // region list so every country/territory with a dial code is selectable.
  {
    code: "AX",
    name: "Åland Islands",
    nationality: "Ålandic",
    dialCode: "+358",
    flag: "🇦🇽",
  },
  {
    code: "AS",
    name: "American Samoa",
    nationality: "American Samoan",
    dialCode: "+1",
    flag: "🇦🇸",
  },
  {
    code: "AD",
    name: "Andorra",
    nationality: "Andorran",
    dialCode: "+376",
    flag: "🇦🇩",
  },
  {
    code: "AO",
    name: "Angola",
    nationality: "Angolan",
    dialCode: "+244",
    flag: "🇦🇴",
  },
  {
    code: "AI",
    name: "Anguilla",
    nationality: "Anguillan",
    dialCode: "+1",
    flag: "🇦🇮",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    nationality: "Antiguan or Barbudan",
    dialCode: "+1",
    flag: "🇦🇬",
  },
  {
    code: "AM",
    name: "Armenia",
    nationality: "Armenian",
    dialCode: "+374",
    flag: "🇦🇲",
  },
  {
    code: "AW",
    name: "Aruba",
    nationality: "Aruban",
    dialCode: "+297",
    flag: "🇦🇼",
  },
  {
    code: "AC",
    name: "Ascension Island",
    nationality: "Ascension Islander",
    dialCode: "+247",
    flag: "🇦🇨",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    nationality: "Azerbaijani",
    dialCode: "+994",
    flag: "🇦🇿",
  },
  {
    code: "BS",
    name: "Bahamas",
    nationality: "Bahamian",
    dialCode: "+1",
    flag: "🇧🇸",
  },
  {
    code: "BH",
    name: "Bahrain",
    nationality: "Bahraini",
    dialCode: "+973",
    flag: "🇧🇭",
  },
  {
    code: "BB",
    name: "Barbados",
    nationality: "Barbadian",
    dialCode: "+1",
    flag: "🇧🇧",
  },
  {
    code: "BY",
    name: "Belarus",
    nationality: "Belarusian",
    dialCode: "+375",
    flag: "🇧🇾",
  },
  {
    code: "BZ",
    name: "Belize",
    nationality: "Belizean",
    dialCode: "+501",
    flag: "🇧🇿",
  },
  {
    code: "BJ",
    name: "Benin",
    nationality: "Beninese",
    dialCode: "+229",
    flag: "🇧🇯",
  },
  {
    code: "BM",
    name: "Bermuda",
    nationality: "Bermudian",
    dialCode: "+1",
    flag: "🇧🇲",
  },
  {
    code: "BT",
    name: "Bhutan",
    nationality: "Bhutanese",
    dialCode: "+975",
    flag: "🇧🇹",
  },
  {
    code: "BO",
    name: "Bolivia",
    nationality: "Bolivian",
    dialCode: "+591",
    flag: "🇧🇴",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    nationality: "Bosnian or Herzegovinian",
    dialCode: "+387",
    flag: "🇧🇦",
  },
  {
    code: "BW",
    name: "Botswana",
    nationality: "Botswanan",
    dialCode: "+267",
    flag: "🇧🇼",
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    nationality: "British Indian Ocean Territory",
    dialCode: "+246",
    flag: "🇮🇴",
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    nationality: "British Virgin Islander",
    dialCode: "+1",
    flag: "🇻🇬",
  },
  {
    code: "BN",
    name: "Brunei",
    nationality: "Bruneian",
    dialCode: "+673",
    flag: "🇧🇳",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    nationality: "Burkinabé",
    dialCode: "+226",
    flag: "🇧🇫",
  },
  {
    code: "BI",
    name: "Burundi",
    nationality: "Burundian",
    dialCode: "+257",
    flag: "🇧🇮",
  },
  {
    code: "KH",
    name: "Cambodia",
    nationality: "Cambodian",
    dialCode: "+855",
    flag: "🇰🇭",
  },
  {
    code: "CM",
    name: "Cameroon",
    nationality: "Cameroonian",
    dialCode: "+237",
    flag: "🇨🇲",
  },
  {
    code: "CV",
    name: "Cape Verde",
    nationality: "Cape Verdean",
    dialCode: "+238",
    flag: "🇨🇻",
  },
  {
    code: "BQ",
    name: "Caribbean Netherlands",
    nationality: "Bonaire Dutch",
    dialCode: "+599",
    flag: "🇧🇶",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    nationality: "Caymanian",
    dialCode: "+1",
    flag: "🇰🇾",
  },
  {
    code: "CF",
    name: "Central African Republic",
    nationality: "Central African",
    dialCode: "+236",
    flag: "🇨🇫",
  },
  {
    code: "TD",
    name: "Chad",
    nationality: "Chadian",
    dialCode: "+235",
    flag: "🇹🇩",
  },
  {
    code: "CL",
    name: "Chile",
    nationality: "Chilean",
    dialCode: "+56",
    flag: "🇨🇱",
  },
  {
    code: "CX",
    name: "Christmas Island",
    nationality: "Christmas Islander",
    dialCode: "+61",
    flag: "🇨🇽",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    nationality: "Cocos Islander",
    dialCode: "+61",
    flag: "🇨🇨",
  },
  {
    code: "KM",
    name: "Comoros",
    nationality: "Comorian",
    dialCode: "+269",
    flag: "🇰🇲",
  },
  {
    code: "CK",
    name: "Cook Islands",
    nationality: "Cook Islander",
    dialCode: "+682",
    flag: "🇨🇰",
  },
  {
    code: "CR",
    name: "Costa Rica",
    nationality: "Costa Rican",
    dialCode: "+506",
    flag: "🇨🇷",
  },
  {
    code: "CI",
    name: "Côte d’Ivoire",
    nationality: "Ivorian",
    dialCode: "+225",
    flag: "🇨🇮",
  },
  {
    code: "CW",
    name: "Curaçao",
    nationality: "Curaçaoan",
    dialCode: "+599",
    flag: "🇨🇼",
  },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    nationality: "Congolese (DRC)",
    dialCode: "+243",
    flag: "🇨🇩",
  },
  {
    code: "DJ",
    name: "Djibouti",
    nationality: "Djiboutian",
    dialCode: "+253",
    flag: "🇩🇯",
  },
  {
    code: "DM",
    name: "Dominica",
    nationality: "Dominican (Dominica)",
    dialCode: "+1",
    flag: "🇩🇲",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    nationality: "Dominican",
    dialCode: "+1",
    flag: "🇩🇴",
  },
  {
    code: "EC",
    name: "Ecuador",
    nationality: "Ecuadorian",
    dialCode: "+593",
    flag: "🇪🇨",
  },
  {
    code: "SV",
    name: "El Salvador",
    nationality: "Salvadoran",
    dialCode: "+503",
    flag: "🇸🇻",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    nationality: "Equatorial Guinean",
    dialCode: "+240",
    flag: "🇬🇶",
  },
  {
    code: "ER",
    name: "Eritrea",
    nationality: "Eritrean",
    dialCode: "+291",
    flag: "🇪🇷",
  },
  {
    code: "SZ",
    name: "Eswatini",
    nationality: "Swazi",
    dialCode: "+268",
    flag: "🇸🇿",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    nationality: "Falkland Islander",
    dialCode: "+500",
    flag: "🇫🇰",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    nationality: "Faroese",
    dialCode: "+298",
    flag: "🇫🇴",
  },
  {
    code: "FJ",
    name: "Fiji",
    nationality: "Fijian",
    dialCode: "+679",
    flag: "🇫🇯",
  },
  {
    code: "GF",
    name: "French Guiana",
    nationality: "French Guianese",
    dialCode: "+594",
    flag: "🇬🇫",
  },
  {
    code: "PF",
    name: "French Polynesia",
    nationality: "French Polynesian",
    dialCode: "+689",
    flag: "🇵🇫",
  },
  {
    code: "GA",
    name: "Gabon",
    nationality: "Gabonese",
    dialCode: "+241",
    flag: "🇬🇦",
  },
  {
    code: "GM",
    name: "Gambia",
    nationality: "Gambian",
    dialCode: "+220",
    flag: "🇬🇲",
  },
  {
    code: "GE",
    name: "Georgia",
    nationality: "Georgian",
    dialCode: "+995",
    flag: "🇬🇪",
  },
  {
    code: "GI",
    name: "Gibraltar",
    nationality: "Gibraltarian",
    dialCode: "+350",
    flag: "🇬🇮",
  },
  {
    code: "GL",
    name: "Greenland",
    nationality: "Greenlandic",
    dialCode: "+299",
    flag: "🇬🇱",
  },
  {
    code: "GD",
    name: "Grenada",
    nationality: "Grenadian",
    dialCode: "+1",
    flag: "🇬🇩",
  },
  {
    code: "GP",
    name: "Guadeloupe",
    nationality: "Guadeloupean",
    dialCode: "+590",
    flag: "🇬🇵",
  },
  {
    code: "GU",
    name: "Guam",
    nationality: "Guamanian",
    dialCode: "+1",
    flag: "🇬🇺",
  },
  {
    code: "GT",
    name: "Guatemala",
    nationality: "Guatemalan",
    dialCode: "+502",
    flag: "🇬🇹",
  },
  {
    code: "GG",
    name: "Guernsey",
    nationality: "Guernsey Islander",
    dialCode: "+44",
    flag: "🇬🇬",
  },
  {
    code: "GN",
    name: "Guinea",
    nationality: "Guinean",
    dialCode: "+224",
    flag: "🇬🇳",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    nationality: "Bissau-Guinean",
    dialCode: "+245",
    flag: "🇬🇼",
  },
  {
    code: "GY",
    name: "Guyana",
    nationality: "Guyanese",
    dialCode: "+592",
    flag: "🇬🇾",
  },
  {
    code: "HT",
    name: "Haiti",
    nationality: "Haitian",
    dialCode: "+509",
    flag: "🇭🇹",
  },
  {
    code: "HN",
    name: "Honduras",
    nationality: "Honduran",
    dialCode: "+504",
    flag: "🇭🇳",
  },
  {
    code: "IM",
    name: "Isle of Man",
    nationality: "Manx",
    dialCode: "+44",
    flag: "🇮🇲",
  },
  {
    code: "JE",
    name: "Jersey",
    nationality: "Jersey Islander",
    dialCode: "+44",
    flag: "🇯🇪",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    nationality: "Kazakhstani",
    dialCode: "+7",
    flag: "🇰🇿",
  },
  {
    code: "KI",
    name: "Kiribati",
    nationality: "I-Kiribati",
    dialCode: "+686",
    flag: "🇰🇮",
  },
  {
    code: "XK",
    name: "Kosovo",
    nationality: "Kosovar",
    dialCode: "+383",
    flag: "🇽🇰",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    nationality: "Kyrgyz",
    dialCode: "+996",
    flag: "🇰🇬",
  },
  {
    code: "LA",
    name: "Laos",
    nationality: "Laotian",
    dialCode: "+856",
    flag: "🇱🇦",
  },
  {
    code: "LS",
    name: "Lesotho",
    nationality: "Basotho",
    dialCode: "+266",
    flag: "🇱🇸",
  },
  {
    code: "LR",
    name: "Liberia",
    nationality: "Liberian",
    dialCode: "+231",
    flag: "🇱🇷",
  },
  {
    code: "LY",
    name: "Libya",
    nationality: "Libyan",
    dialCode: "+218",
    flag: "🇱🇾",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    nationality: "Liechtensteiner",
    dialCode: "+423",
    flag: "🇱🇮",
  },
  {
    code: "MO",
    name: "Macau",
    nationality: "Macanese",
    dialCode: "+853",
    flag: "🇲🇴",
  },
  {
    code: "MG",
    name: "Madagascar",
    nationality: "Malagasy",
    dialCode: "+261",
    flag: "🇲🇬",
  },
  {
    code: "MW",
    name: "Malawi",
    nationality: "Malawian",
    dialCode: "+265",
    flag: "🇲🇼",
  },
  {
    code: "MV",
    name: "Maldives",
    nationality: "Maldivian",
    dialCode: "+960",
    flag: "🇲🇻",
  },
  {
    code: "ML",
    name: "Mali",
    nationality: "Malian",
    dialCode: "+223",
    flag: "🇲🇱",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    nationality: "Marshallese",
    dialCode: "+692",
    flag: "🇲🇭",
  },
  {
    code: "MQ",
    name: "Martinique",
    nationality: "Martinican",
    dialCode: "+596",
    flag: "🇲🇶",
  },
  {
    code: "MR",
    name: "Mauritania",
    nationality: "Mauritanian",
    dialCode: "+222",
    flag: "🇲🇷",
  },
  {
    code: "MU",
    name: "Mauritius",
    nationality: "Mauritian",
    dialCode: "+230",
    flag: "🇲🇺",
  },
  {
    code: "YT",
    name: "Mayotte",
    nationality: "Mahoran",
    dialCode: "+262",
    flag: "🇾🇹",
  },
  {
    code: "FM",
    name: "Micronesia",
    nationality: "Micronesian",
    dialCode: "+691",
    flag: "🇫🇲",
  },
  {
    code: "MD",
    name: "Moldova",
    nationality: "Moldovan",
    dialCode: "+373",
    flag: "🇲🇩",
  },
  {
    code: "MC",
    name: "Monaco",
    nationality: "Monégasque",
    dialCode: "+377",
    flag: "🇲🇨",
  },
  {
    code: "MN",
    name: "Mongolia",
    nationality: "Mongolian",
    dialCode: "+976",
    flag: "🇲🇳",
  },
  {
    code: "ME",
    name: "Montenegro",
    nationality: "Montenegrin",
    dialCode: "+382",
    flag: "🇲🇪",
  },
  {
    code: "MS",
    name: "Montserrat",
    nationality: "Montserratian",
    dialCode: "+1",
    flag: "🇲🇸",
  },
  {
    code: "MZ",
    name: "Mozambique",
    nationality: "Mozambican",
    dialCode: "+258",
    flag: "🇲🇿",
  },
  {
    code: "MM",
    name: "Myanmar",
    nationality: "Burmese",
    dialCode: "+95",
    flag: "🇲🇲",
  },
  {
    code: "NA",
    name: "Namibia",
    nationality: "Namibian",
    dialCode: "+264",
    flag: "🇳🇦",
  },
  {
    code: "NR",
    name: "Nauru",
    nationality: "Nauruan",
    dialCode: "+674",
    flag: "🇳🇷",
  },
  {
    code: "NC",
    name: "New Caledonia",
    nationality: "New Caledonian",
    dialCode: "+687",
    flag: "🇳🇨",
  },
  {
    code: "NI",
    name: "Nicaragua",
    nationality: "Nicaraguan",
    dialCode: "+505",
    flag: "🇳🇮",
  },
  {
    code: "NE",
    name: "Niger",
    nationality: "Nigerien",
    dialCode: "+227",
    flag: "🇳🇪",
  },
  {
    code: "NU",
    name: "Niue",
    nationality: "Niuean",
    dialCode: "+683",
    flag: "🇳🇺",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    nationality: "Norfolk Islander",
    dialCode: "+672",
    flag: "🇳🇫",
  },
  {
    code: "KP",
    name: "North Korea",
    nationality: "North Korean",
    dialCode: "+850",
    flag: "🇰🇵",
  },
  {
    code: "MK",
    name: "North Macedonia",
    nationality: "Macedonian",
    dialCode: "+389",
    flag: "🇲🇰",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    nationality: "Northern Mariana Islander",
    dialCode: "+1",
    flag: "🇲🇵",
  },
  {
    code: "OM",
    name: "Oman",
    nationality: "Omani",
    dialCode: "+968",
    flag: "🇴🇲",
  },
  {
    code: "PW",
    name: "Palau",
    nationality: "Palauan",
    dialCode: "+680",
    flag: "🇵🇼",
  },
  {
    code: "PA",
    name: "Panama",
    nationality: "Panamanian",
    dialCode: "+507",
    flag: "🇵🇦",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    nationality: "Papua New Guinean",
    dialCode: "+675",
    flag: "🇵🇬",
  },
  {
    code: "PY",
    name: "Paraguay",
    nationality: "Paraguayan",
    dialCode: "+595",
    flag: "🇵🇾",
  },
  {
    code: "PE",
    name: "Peru",
    nationality: "Peruvian",
    dialCode: "+51",
    flag: "🇵🇪",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    nationality: "Puerto Rican",
    dialCode: "+1",
    flag: "🇵🇷",
  },
  {
    code: "CG",
    name: "Republic of the Congo",
    nationality: "Congolese",
    dialCode: "+242",
    flag: "🇨🇬",
  },
  {
    code: "RE",
    name: "Réunion",
    nationality: "Réunionese",
    dialCode: "+262",
    flag: "🇷🇪",
  },
  {
    code: "RW",
    name: "Rwanda",
    nationality: "Rwandan",
    dialCode: "+250",
    flag: "🇷🇼",
  },
  {
    code: "SH",
    name: "Saint Helena",
    nationality: "Saint Helenian",
    dialCode: "+290",
    flag: "🇸🇭",
  },
  {
    code: "MF",
    name: "Saint Martin",
    nationality: "Saint Martin Islander",
    dialCode: "+590",
    flag: "🇲🇫",
  },
  {
    code: "WS",
    name: "Samoa",
    nationality: "Samoan",
    dialCode: "+685",
    flag: "🇼🇸",
  },
  {
    code: "SM",
    name: "San Marino",
    nationality: "Sammarinese",
    dialCode: "+378",
    flag: "🇸🇲",
  },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    nationality: "São Toméan",
    dialCode: "+239",
    flag: "🇸🇹",
  },
  {
    code: "SN",
    name: "Senegal",
    nationality: "Senegalese",
    dialCode: "+221",
    flag: "🇸🇳",
  },
  {
    code: "SC",
    name: "Seychelles",
    nationality: "Seychellois",
    dialCode: "+248",
    flag: "🇸🇨",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    nationality: "Sierra Leonean",
    dialCode: "+232",
    flag: "🇸🇱",
  },
  {
    code: "SX",
    name: "Sint Maarten",
    nationality: "Sint Maartener",
    dialCode: "+1",
    flag: "🇸🇽",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    nationality: "Solomon Islander",
    dialCode: "+677",
    flag: "🇸🇧",
  },
  {
    code: "SO",
    name: "Somalia",
    nationality: "Somali",
    dialCode: "+252",
    flag: "🇸🇴",
  },
  {
    code: "SS",
    name: "South Sudan",
    nationality: "South Sudanese",
    dialCode: "+211",
    flag: "🇸🇸",
  },
  {
    code: "BL",
    name: "St. Barthélemy",
    nationality: "Saint Barthélemy Islander",
    dialCode: "+590",
    flag: "🇧🇱",
  },
  {
    code: "KN",
    name: "St. Kitts and Nevis",
    nationality: "Kittitian or Nevisian",
    dialCode: "+1",
    flag: "🇰🇳",
  },
  {
    code: "LC",
    name: "St. Lucia",
    nationality: "Saint Lucian",
    dialCode: "+1",
    flag: "🇱🇨",
  },
  {
    code: "PM",
    name: "St. Pierre and Miquelon",
    nationality: "Saint-Pierrais",
    dialCode: "+508",
    flag: "🇵🇲",
  },
  {
    code: "VC",
    name: "St. Vincent and Grenadines",
    nationality: "Saint Vincentian",
    dialCode: "+1",
    flag: "🇻🇨",
  },
  {
    code: "SD",
    name: "Sudan",
    nationality: "Sudanese",
    dialCode: "+249",
    flag: "🇸🇩",
  },
  {
    code: "SR",
    name: "Suriname",
    nationality: "Surinamese",
    dialCode: "+597",
    flag: "🇸🇷",
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    nationality: "Svalbard resident",
    dialCode: "+47",
    flag: "🇸🇯",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    nationality: "Tajik",
    dialCode: "+992",
    flag: "🇹🇯",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    nationality: "Timorese",
    dialCode: "+670",
    flag: "🇹🇱",
  },
  {
    code: "TG",
    name: "Togo",
    nationality: "Togolese",
    dialCode: "+228",
    flag: "🇹🇬",
  },
  {
    code: "TK",
    name: "Tokelau",
    nationality: "Tokelauan",
    dialCode: "+690",
    flag: "🇹🇰",
  },
  {
    code: "TO",
    name: "Tonga",
    nationality: "Tongan",
    dialCode: "+676",
    flag: "🇹🇴",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    nationality: "Trinidadian or Tobagonian",
    dialCode: "+1",
    flag: "🇹🇹",
  },
  {
    code: "TA",
    name: "Tristan da Cunha",
    nationality: "Tristanian",
    dialCode: "+290",
    flag: "🇹🇦",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    nationality: "Turkmen",
    dialCode: "+993",
    flag: "🇹🇲",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    nationality: "Turks and Caicos Islander",
    dialCode: "+1",
    flag: "🇹🇨",
  },
  {
    code: "TV",
    name: "Tuvalu",
    nationality: "Tuvaluan",
    dialCode: "+688",
    flag: "🇹🇻",
  },
  {
    code: "VI",
    name: "U.S. Virgin Islands",
    nationality: "U.S. Virgin Islander",
    dialCode: "+1",
    flag: "🇻🇮",
  },
  {
    code: "UY",
    name: "Uruguay",
    nationality: "Uruguayan",
    dialCode: "+598",
    flag: "🇺🇾",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    nationality: "Uzbek",
    dialCode: "+998",
    flag: "🇺🇿",
  },
  {
    code: "VU",
    name: "Vanuatu",
    nationality: "Ni-Vanuatu",
    dialCode: "+678",
    flag: "🇻🇺",
  },
  {
    code: "VA",
    name: "Vatican City",
    nationality: "Vatican",
    dialCode: "+39",
    flag: "🇻🇦",
  },
  {
    code: "VE",
    name: "Venezuela",
    nationality: "Venezuelan",
    dialCode: "+58",
    flag: "🇻🇪",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    nationality: "Wallisian or Futunan",
    dialCode: "+681",
    flag: "🇼🇫",
  },
  {
    code: "EH",
    name: "Western Sahara",
    nationality: "Sahrawi",
    dialCode: "+212",
    flag: "🇪🇭",
  },
];

/** Alphabetical list of nationality strings (e.g. for a <select>). */
export const NATIONALITIES = COUNTRIES.map((c) => c.nationality).sort((a, b) =>
  a.localeCompare(b),
);

/** Look up a country by its ISO alpha-2 code. */
export function getCountryByCode(code) {
  if (!code) return null;
  const up = String(code).toUpperCase();
  return COUNTRIES.find((c) => c.code === up) || null;
}

/** Look up a country by nationality/demonym (case-insensitive). */
export function getCountryByNationality(nationality) {
  if (!nationality) return null;
  const lc = String(nationality).toLowerCase();
  return COUNTRIES.find((c) => c.nationality.toLowerCase() === lc) || null;
}

// Several territories share a dial code. With the full ISO list (BUG-006) a plain
// first-match could resolve "+1" to a Caribbean territory, so shared codes map to
// their primary country explicitly; anything unlisted falls back to first match.
const DIAL_CODE_PRIMARY = {
  "+1": "US",   // United States (also Canada + Caribbean territories)
  "+7": "RU",   // Russia (also Kazakhstan)
  "+39": "IT",  // Italy (also Vatican City)
  "+44": "GB",  // United Kingdom (also Guernsey/Jersey/Isle of Man)
  "+47": "NO",  // Norway (also Svalbard)
  "+61": "AU",  // Australia (also Christmas/Cocos Islands)
  "+212": "MA", // Morocco (also Western Sahara)
  "+262": "RE", // Réunion (also Mayotte)
  "+290": "SH", // Saint Helena (also Tristan da Cunha)
  "+358": "FI", // Finland (also Åland)
  "+590": "GP", // Guadeloupe (also Saint Barthélemy / Saint Martin)
  "+599": "CW", // Curaçao (also Caribbean Netherlands)
};

/** Look up a country by dial code (e.g. "+44"). Shared codes → primary country. */
export function getCountryByDialCode(dialCode) {
  if (!dialCode) return null;
  const dc = String(dialCode).trim();
  const withPlus = dc.startsWith("+") ? dc : `+${dc}`;
  const primary = DIAL_CODE_PRIMARY[withPlus];
  if (primary) {
    const match = COUNTRIES.find((c) => c.code === primary);
    if (match) return match;
  }
  return COUNTRIES.find((c) => c.dialCode === withPlus) || null;
}

/** Sorted list of country names (e.g. for a Country <select>). */
export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name).sort((a, b) =>
  a.localeCompare(b),
);

/** Default dial code (UK) — sensible default for a UK-based CRM. */
export const DEFAULT_COUNTRY = "GB";

/**
 * Validate a phone number given a separate dial code + national number,
 * using libphonenumber-js for strict per-country rules.
 *
 * @param {string} dialCode  e.g. "+44"
 * @param {string} national  local digits the user typed, e.g. "7911123456"
 * @returns {boolean} true when the combined number is valid for that region.
 */
export function isValidPhone(dialCode, national) {
  const digits = String(national || "").replace(/[^\d]/g, "");
  if (!digits) return false;
  const country = getCountryByDialCode(dialCode);
  try {
    // Prefer region-based validation; fall back to E.164 string.
    if (country) return isValidPhoneNumber(digits, country.code);
    const e164 = `${String(dialCode || "").trim()}${digits}`;
    return isValidPhoneNumber(e164);
  } catch {
    return false;
  }
}
